create table public.desert (
    id bigint generated by default as identity primary key,
    name text not null,
    field_jsons jsonb[] not null
);

create table public.game (
    id bigint generated by default as identity primary key,
    progress smallint not null default '0'::smallint,
    json jsonb not null,
    desert_id bigint not null references public.desert(id)
);

create table public.game_state (
    id bigint generated by default as identity primary key,
    game_id bigint not null references public.game(id),
    "index" bigint not null,
    field_jsons jsonb[] not null,
    player_jsons jsonb[] not null
);

create table public.player_step (
    id bigint generated by default as identity primary key,
    game_state_id bigint references public.game_state(id),
    json jsonb,
    player_id bigint
);

create or replace function public.save_gamestate(
    game_id bigint,
    "index" bigint,
    field_jsons jsonb[],
    player_jsons jsonb[],
    player_ids bigint[]
)
returns void
language plpgsql
as $$
declare
    new_game_state_id int8;
    pid int8;
begin
    insert into game_state (game_id, index, field_jsons, player_jsons)
    values (game_id, index, field_jsons, player_jsons)
    on conflict (id) do update
        set game_id = excluded.game_id,
            index = excluded.index,
            field_jsons = excluded.field_jsons,
            player_jsons = excluded.player_jsons
    returning id into new_game_state_id;

    foreach pid in array player_ids loop
        insert into player_step (game_state_id, player_id, json)
        values (new_game_state_id, pid, '"{}"'::jsonb);
    end loop;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('svgs', 'svgs', true, 52428800, array['image/svg+xml'])
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on
    public.desert,
    public.game,
    public.game_state,
    public.player_step
to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on function public.save_gamestate(bigint, bigint, jsonb[], jsonb[], bigint[]) to anon, authenticated;

alter table public.desert enable row level security;
alter table public.game enable row level security;
alter table public.game_state enable row level security;
alter table public.player_step enable row level security;

create policy "Enable read access for all users"
on public.desert
for select
to public
using (true);

create policy "Enable all for authenticated users only"
on public.game
for all
to authenticated
using (true);

create policy "Enable all for authenticated users only"
on public.game_state
for all
to authenticated
using (true);

create policy "Enable all for authenticated users only"
on public.player_step
for all
to authenticated
using (true);

create policy "Give anon users access to JPG images in folder 23xjj_0"
on storage.objects
for select
to public
using ((bucket_id = 'svgs') and (storage.extension(name) = 'svg'));

create policy "Give anon users access to JPG images in folder 23xjj_1"
on storage.objects
for insert
to public
with check ((bucket_id = 'svgs') and (storage.extension(name) = 'svg'));
